export const cities = [
    { title: "Angren shahri" },
    { title: "Bekobod shahri va tumani" },
    { title: "Bo'ka shahri va tumani" },
    { title: "Do'stobod shahri" },
    { title: "Keles shahri" },
    { title: "Olmaliq shahri" },
    { title: "Oqqo'rg'on shahri va tumani" },
    { title: "Ohangaron shahri va tumani" },
    { title: "Parkent shahri va tumani" },
    { title: "Piskent shahri va tumani" },
    { title: "Toshkent shahri" },
    { title: "To'ytepa shahri" },
    { title: "Chinoz shahri va tumani" },
    { title: "Chirchiq shahri" },
    { title: "Yangiyo'l shahri" },
    { title: "Yangiobod shahri" },
    { title: "G'azalkent shahri" },
    { title: "Alimkent shaharchasi" },
    { title: "Bo'zsuv shaharchasi" },
    { title: "Gulbahor shaharchasi" },
    { title: "Zafar shaharchasi" },
    { title: "Iskandar shaharchasi" },
    { title: "Krasnogorsk shaharchasi" },
    { title: "Nurobod shaharchasi" },
    { title: "Olmazor shaharchasi" },
    { title: "Salor shaharchasi" },
    { title: "Tuyabo'g'iz shaharchasi" },
    { title: "Chig'iriq shaharchasi" },
    { title: "Chorvoq shaharchasi" },
    { title: "Eshonguzar shaharchasi" },
    { title: "Yangibozor shaharchasi" },
    { title: "Yangi chinoz shaharchasi" },
    { title: "Yangihayot shaharchasi" },
    { title: "O'rtaovul shaharchasi" },
    { title: "Qibray shaharchasi va tumani" },
    { title: "Bo'stonliq tumani" },
    { title: "Zangiota tumani" },
    { title: "Yuqori Chirchiq tumani" },
    { title: "Yangiyo'l tumani" },
    { title: "O'rta Chirchiq tumani" },
    { title: "Quyi Chirchiq tumani" },
  ];